# Generated by Django 5.0.4 on 2024-04-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='avatar',
        ),
        migrations.AddField(
            model_name='users',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='users',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
