# Generated by Django 5.0.4 on 2024-04-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_avatar_users_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=1000, upload_to='avatars'),
        ),
    ]
