# Generated by Django 5.0.4 on 2024-04-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='notification',
            name='comment_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
